### ISSUE TITLE
error starting new script runner

### ISSUE THREAD

**Issue by dosaboy** [canonical/athena-core#70]
I am seeing the following in the athena-processor typically a few days after a restart:

{"level":"info","msg":"Downloading 'uploads/sosreport-XXX.tar.xz' to '/tmp/athena/athena-report-sosreports865620253'","time":"2023-09-18T07:18:54Z"}
{"level":"error","msg":"Failed to get new runner: Not Found - http-code: 404","time":"2023-09-18T07:18:54Z"}
{"component":"pubsub","duration":266873658,"err":"Not Found - http-code: 404","handler":"athena-processor-30389025ce78","id":"436","level":"error","metadata":{"x-audit-user":""},"msg":"Failed Processing PubSub Msg","stack":"goroutine 23 [running]:
runtime/debug.Stack(0xb28700, 0xc0006c9a68, 0xbdb487)
	/opt/hostedtoolcache/go/1.16.15/x64/src/runtime/debug/stack.go:24 +0x9f
github.com/lileio/pubsub/v2/middleware/logrus.Middleware.SubscribeInterceptor.func1(0xcc2990, 0xc000026030, 0xc0004b15ac, 0x3, 0xc000321560, 0xc00069c120, 0x105, 0x120, 0xc0003a60d8, 0xc0000bc8d0, ...)
	/home/runner/go/pkg/mod/github.com/lileio/pubsub/v2@v2.5.0/middleware/logrus/logrus.go:57 +0x537
github.com/lileio/pubsub/v2.chainSubscriberMiddleware.func1.1(0xcc2990, 0xc000026030, 0xc0004b15ac, 0x3, 0xc000321560, 0xc00069c120, 0x105, 0x120, 0xc0003a60d8, 0xc0000bc8d0, ...)
	/home/runner/go/pkg/mod/github.com/lileio/pubsub/v2@v2.5.0/subscribe.go:167 +0x170
github.com/lileio/pubsub/v2/providers/nats.(*Nats).Subscribe.func1(0xc00015a230)
	/home/runner/go/pkg/mod/github.com/lileio/pubsub/v2@v2.5.0/providers/nats/nats.go:120 +0x58b
github.com/nats-io/stan%2ego.(*conn).processMsg(0xc00054a000, 0xc000276120)
	/home/runner/go/pkg/mod/github.com/nats-io/stan.go@v0.8.3/stan.go:879 +0x2f9
github.com/nats-io/nats%2ego.(*Conn).waitForMsgs(0xc00054c000, 0xc00041c0c0)
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.1-0.20210419223411-20527524c393/nats.go:2412 +0x342
created by github.com/nats-io/nats%2ego.(*Conn).subscribeLocked
	/home/runner/go/pkg/mod/github.com/nats-io/nats.go@v1.10.1-0.20210419223411-20527524c393/nats.go:3491 +0x4a5
","time":"2023-09-18T07:18:54Z","topic":"sosreports"} 

This seems to result in the failure to run any further scripts until a manual restart is performed.

**Comment by dosaboy** [comment]
error is happening at https://github.com/canonical/athena-core/blob/368a4cc14e14234213ec15a55dd42524fb942469/pkg/processor/processor.go#L330

**Comment by nicolasbock** [comment]
What do you mean with that no further scripts are run? In my local testing I can still add files to the uploads folder and athena picks those up.
